### ISSUE TITLE
Expressions in `<head>` causes elements to end up in `<body>`

### ISSUE THREAD

**Issue by donnikitos** [withastro/compiler#985] opened 2024-03-15 21:07 UTC
### Astro Info

```block
Astro                    v4.5.5
Node                     v21.6.2
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/preact
                         astro-reroute
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Chromium, Firefox

### Describe the Bug

Updated Astro from 4.0.8 to latest 4.5.4 and suddenly browsers receive files with broken utf-8 characters:
![image](https://github.com/withastro/astro/assets/5833538/f27c4306-4a29-4299-ad1c-c051e6ef2b0b)
![image](https://github.com/withastro/astro/assets/5833538/8a93c1e7-1a47-4a40-a6b2-b49b400632e0)

`<meta charset="UTF-8" />` is set.
Input files are encoded in proper UTF-8 charset.

For now my only solution for deployment is to enforce UTF-8 via .htaccess headers.
Dev server still displays broken characters.

### What's the expected result?

During development and after build non-ASCI character should be properly encoded.
For example:
 - `Ã¶` should be `ö`
 - `Ã¼` should be `ü`
 - ...

### Link to Minimal Reproducible Example

https://github.com/donnikitos/astro-utf-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cdtut** [comment] 2024-03-27 21:56
@MoustaphaDev should merge https://github.com/withastro/compiler/issues/982 he thinks is related to this.

**Comment by cdtut** [comment] 2024-03-28 19:25
@Princesseuh Can priority level be urgent? Can't upgrade after 4.2.1 because everything break.

**Comment by matthewp** [comment] 2024-03-28 19:46
This simple example doesn't reproduce: https://stackblitz.com/edit/github-pfaayw?file=src%2Fpages%2Findex.astro

Can anyone come up with a minimal repro at the level with it?

**Comment by cdtut** [comment] 2024-03-28 20:26
I add this inside `<head>` to see issue from `astro build`.

```
{[1, 2, 3].map(() => <>
    {<meta name="" content="" />}
</>)}
```

**Comment by matthewp** [comment] 2024-03-29 12:22
I updated this demo to use that: https://stackblitz.com/edit/github-pfaayw?file=src%2Fpages%2Findex.astro,package.json

Still in the head. Can you adjust my demo to get it to break?

**Comment by matthewp** [comment] 2024-03-29 12:56
I was able to reproduce it down with this: https://stackblitz.com/edit/github-pfaayw-axdvrr?file=src%2Fpages%2Findex.astro,package.json

**Comment by matthewp** [comment] 2024-03-29 14:14
Unfortunately that PR breaks a bunch of tests in core. There might be a way to fix this issue differently, though.

**Comment by matthewp** [comment] 2024-03-29 15:03
Pretty sure this is the culprit: https://github.com/withastro/compiler/commit/14ccba5d4dc0c962af247eff7cb0d7c199302538

**Comment by cdtut** [comment] 2024-03-29 18:32
If test pass will PR be in next astro release?

**Comment by matthewp** [comment] 2024-03-29 18:47
I'll create a preview release and have a few people test it. But yes, it will be soon (probably next week) if everything looks ok.

**Comment by matthewp** [comment] 2024-03-29 19:12
@cdtut you can test by install `astro@experimental--head-body-content`.

I tested with this demo, which is fixed now: https://stackblitz.com/edit/github-pfaayw-axdvrr?file=src%2Fpages%2Findex.astro,package.json

**Comment by deeprobin** [comment] 2024-03-29 21:35
@matthewp's fix works for my case :smile:.
Thank you!

**Closed** 2024-04-01 13:40 UTC
Labels: needs triage, needs repro
