### ISSUE TITLE
Compiler error when a JS expression contains <=

### ISSUE THREAD

**Issue by giuseppelt** [withastro/compiler#762] opened 2023-03-16 21:04 UTC
### What version of `astro` are you using?

2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Inside an astro component, this will not compile:
```astro
---
const array = [1,2,3,4];
---
<body>
    {
      array.filter(x => x <= 3)
        .map(x => <span>{x}</span>)
    }
</body>
```
The error:
`Unable to assign attributes when using <> Fragment shorthand syntax!`

Only the `<=` produces the error. Other operators work fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6n1a9b-wnnkry?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by OverflowCat** [comment] 2023-07-25 10:10
I also encountered this issue today. Adding parentheses around the conditions can sometimes be another temporary workaround, but parentheses will be formatted.

**Comment by Princesseuh** [comment] 2023-11-12 22:11
Closing as duplicate of https://github.com/withastro/compiler/issues/723

**Closed by Princesseuh** 2023-11-12 22:11 UTC
Labels: - P4: important

**Comment by xDaniel17** [comment] 2025-02-12 21:47
Same problem:

```Astro
    <div class="mt-4">
          {
              isSale &&
              today >= startDate &&
              today < endDate ? (
                  <div class="text-lg font-medium text-gray-900 dark:text-gray-100">
                      <p>
                          <span class="line-through text-gray-500 dark:text-gray-400">
                              ${regularPrice.toFixed(2)}
                          </span>
                      </p>
                      <p>
                          ${price.toFixed(2)}
                      </p>
                  </div>
              ) : (
                  <p class="text-xl font-medium text-gray-900 dark:text-gray-100">
                      ${regularPrice.toFixed(2)}
                  </p>
              )
          }
      </div>
```
