### ISSUE TITLE
Build fails when exporting a type using MarkdownLayoutProps

### ISSUE THREAD

**Issue by phelipetls** [withastro/compiler#763] opened 2022-11-13 01:58 UTC
### What version of `astro` are you using?

1.6.6

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Exporting a type using `MarkdownLayoutProps` causes the following error.

```
[plugin:astro:build] Expected ">" but found "const"
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yaiimj?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-11-12 22:14
Could be related to https://github.com/withastro/compiler/issues/554

**Comment by Princesseuh** [comment] 2024-07-23 12:01
Confirming that this is a duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2024-07-23 12:01 UTC
Labels: - P2: has workaround
