### ISSUE TITLE
🐛 BUG: Cannot read properties of undefined (reading 'Symbol(astro:slot-string)')

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/compiler#905] opened 2023-12-13 17:29 UTC
### What version of `@astrojs/compiler` are you using?

2.3.2

### What package manager are you using?

npm

### What operating system are you using?

Linux, Windows

### Describe the Bug

The following
```html
<span class="before:content-['\02022']">TEST</span>
```
throws
```
Cannot read properties of undefined (reading 'Symbol(astro:slot-string)')
```
but updating to the following fixes it.
```html
<span class="before:content-['\\02022']">TEST</span>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-laa84w?file=src%2Fpages%2Findex.astro

**Comment by MoustaphaDev** [comment] 2023-12-18 23:06
I think this is a duplicate of #914

**Comment by florian-lefebvre** [comment] 2023-12-19 06:26
You're right! I searched for it before opening but it didn't appear. Closing as duplicate

**Closed** 2023-12-19 06:27 UTC
Labels: needs triage
