### ISSUE TITLE
🐛 BUG: astro check:  fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by Altair-Bueno** [withastro/compiler#806] opened 2023-06-09 19:52 UTC
### What version of `@astrojs/compiler` are you using?

v2.6.2

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

```
$ pnpm astro check

> temp@0.0.1 astro /Users/compux72/Developer/svelte-gallery
> astro "check"

09:49:30 PM [check] Checking files
09:49:31 PM [content] No content directory found. Skipping type generation.
✔  Getting diagnostics for Astro files in /Users/compux72/Developer/svelte-gallery/…
09:49:33 PM [diagnostics] Result (2 files): 
- 0 errors
- 0 warnings
- 0 hints

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x59
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x4ed
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:236 +0xa29

goroutine 6 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x4a
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1e5

goroutine 7 [chan receive]:
main.(*serviceType).sendRequest(0xc000023e90, {0x14f2f80, 0xc000174240})
        github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0xfa
main.runService.func3()
        github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x39
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x31c
```

### Link to Minimal Reproducible Example

https://github.com/Altair-Bueno/svelte-gallery/tree/43e01e4d7435ee784522de7f8b3659eb35d52de9

**Comment by bluwy** [comment] 2023-06-10 02:03
Duplicate of https://github.com/withastro/astro/issues/6306

**Closed by bluwy** 2023-06-10 02:03 UTC
