### ISSUE TITLE
Expected ";" but found "const" - typescript transformer

### ISSUE THREAD

**Issue by bartlomiejzuber** [withastro/compiler#997] opened 2024-04-03 09:44 UTC
### What version of `@astrojs/compiler` are you using?

2.8.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug
In this code sample, the export statement is hoisted, but `as const` is not.
```astro
---
export const allAboutUsPreviewCards = [
] as const;
---
```
`as const` is correctly hoisted if the const declaration is only takes up one line.

### Link to Minimal Reproducible Example

[Live Astro Compiler](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMTUsMTA5LDEzLDEwMiwyLDMsMTAxLDE0NSw3Nyw3OSwyLDQ5LDE2LDEzNCwyNTUsMjAyLDE2NiwxMDMsMjI0LDE2MCwxNTgsNDgsMzAsOCwxMjYsMTk2LDE5NiwzLDk3LDY1LDc3LDE5NiwxOTUsMjA4LDE0LDE2Niw3MywxODMsMjExLDIwNCwyMDQsMTAsMjA5LDI0OCwyMjMsMTU3LDUsNSwxMzMsOTksMTY3LDIwNywyNTEsMjA5LDIzMywxNjcsMjQzLDQ1LDUxLDEwMiwyOSw4Myw4Myw5OCw2NiwxMjYsNjgsMTUwLDcyLDIxNywxMywyMjEsMjE3LDIyNCwxMjQsMTEyLDIyNSwxMjIsMjA2LDgzLDY0LDU5LDI0NiwyNTEsMjUzLDY5LDE5OCw3NywzMywyMTQsMjAyLDgzLDIyLDE3MywzMiwxNjUsMjA5LDE0Niw5MCwxNTcsMjAzLDEzMiwyNDEsNjEsMjI2LDEyMiwxMiwyOCwxNjQsMTg2LDE3MCw5NCwyMiwyNDksMTgxLDIsMjE3LDk3LDE1MSwxMzksMTg4LDE0OSwxNTQsMjExLDE1NCw1Niw2MCw0OSwxNDgsMTMwLDE5MywxMyw4NywxNDQsNCwxMjMsMTc0LDIxNywxODUsNDMsNjcsMTUwLDIxLDExMyw5OSw4OCwxLDIyLDE1NiwxNDQsNjgsMjIxLDIyLDI0OSwxLDI0NywxOTYsMTI1LDg2LDIyOCwxMiwxMDUsNjIsMTI1LDQ4LDE2MSwyNDEsNDMsMjM1LDE1NywxNjEsMjMzLDEwOCwxODYsNiwzLDE2LDEwMSwxNzgsMTIxLDU0LDI0LDgyLDI1MiwxOTIsMTEyLDEyMywzMiwxMDgsMTkwLDExOSwxNzAsMTY5LDEwMSwxNDMsMTMsMTQ4LDIxMSwxNDQsODEsMjMxLDExMywxNTEsMTA0LDksMTA1LDE5NiwxMTEsMTE0LDM2LDIzNiwxNTAsNSw5NCw3OSwxMDEsODMsMTQ4LDU0LDEwNSwyMzcsMjAxLDE1OCw4OCwzOSw1OCwxNiwyMjEsMTIyLDE3NCw4MSwxOTMsMTM4LDEzMiwyOSwxMDAsMTU4LDIwMiwxNzMsOTMsOSwzOCwyNDQsMTM4LDk3LDI0NiwxMDcsNTAsMTMxLDE2NSwyMjksMTA5LDIxNSwyNTQsMjMxLDE4MiwxMjYsMjU0LDU1LDIyMyw3MSwyMjIsMTA4LDEwLDExNCwxMDgsMjM2LDExLDMzLDc3LDQ5LDcsMjI4LDIxOCwxMTUsNDQsMjIsMjIxLDIxNywxMjcsMTI1LDMsNDQsMjIwLDEyMCw5MSwyMjUsMSwwLDBd)

**Comment by lilnasy** [comment] 2024-04-03 14:54
Updated the issue description to focus on incorrect compilation.

**Comment by Princesseuh** [comment] 2024-12-04 11:08
Duplicate of https://github.com/withastro/compiler/issues/554

**Closed by Princesseuh** 2024-12-04 11:08 UTC
Labels: - P4: important
