### ISSUE TITLE
🐛 BUG: import.meta.env.VITE_XXX doesn't always work in markdown files

### ISSUE THREAD

**Issue by thobson** [withastro/compiler#404] opened 2022-05-20 12:42 UTC
### What version of `@astrojs/compiler` are you using?

1.0.0-beta.31

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

This simple page fails

```
---
title: Broken
layout: ../layouts/CMS.astro
---

Not working
{import.meta.env.VITE_EMAIL}
```
with the error 
```
Parse failure: Unexpected token (1:61)
Contents of line 1: export const metadata = { "headers": [], "source": "Email: {"john.doe@gmail.com"}", "html": "<p>Email: {"john.doe@gmail.com"}</p>" };
```
However I have another more complex page in which {import.meta.env.VITE_EMAIL} works:

```
---
title: Working
layout: ../layouts/CMS.astro
---

[privacy policy](/privacy)

Dispute"

Email: {import.meta.env.VITE_EMAIL}
```

The problem is obviously the quotes around the email address but I can't figure out why it works sometime 🤔 From what I can see it works if I have both a link AND a quote in the markdown. 

Here is my .env

```
VITE_EMAIL=john.doe@gmail.com
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gy8qes-uf7the?file=src/pages/working.md

**Comment by ran-dall** [comment] 2022-07-14 22:12
@thobson, I'm currently taking a look at this. Sorry for the delay.

**Comment by ran-dall** [comment] 2022-07-15 00:31
@thobson So, currently, using `environment variables` from a `.env` file (through Vite) is broken when trying to use markdown files. However, this isn't caused by the compiler, but rather, our handling of markdown that's handled via Astro's Markdown integration, here: https://github.com/withastro/astro/blob/f7fa39e682f6039e4f14102f8cd69ff2ba71b3e3/packages/astro/src/vite-plugin-markdown/index.ts#L246.

After some discussion with @hippotastic on Discord, the most optimal way around this would be to create a `.astro` component`. I fixed your example with that workaround here: https://github.com/ran-dall/astro-compiler-404.

I hope that address the immediate issue.

**Comment by thobson** [comment] 2022-07-15 14:24
Thanks for taking a look @ran-dall - I actually ended up doing exactly as you suggest.

**Comment by natemoo-re** [comment] 2022-11-16 14:25
Closing this since our Markdown handling has been overhauled since v1.0.0 stable. This should be fixed!

**Closed by natemoo-re** 2022-11-16 14:25 UTC
